---
kind: pipeline
type: kubernetes
name: DCU-Regression
trigger:
  branch:
    - main
  event:
    - push
steps:
  - name: execute tests
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation:${DRONE_COMMIT_SHA}
    commands:
      - sh bin/dcu.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username

  - name: upload serenity report
    image: amazon/aws-cli
    commands:
      - > # yaml folded style
        aws s3 cp
        --recursive /drone/src/target/site/serenity/ s3://cs-integration-testing-s3/serenity-reports/$${DRONE_BUILD_NUMBER}_DCU/
        --sse aws:kms
        --sse-kms-key-id $${AWS_KMS_KEY}
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_KMS_KEY:
        from_secret: aws_kms_key_id
    depends_on:
      - execute tests
    when:
      status:
        - success
        - failure

services:
  - name: selenium
    image: selenium/hub

  - name: chrome33
    image: selenium/node-chrome
    environment:
      DISPLAY: :99.0
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444

---
kind: pipeline
type: kubernetes
name: CS-Regression
depends_on:
  - DCU-Regression
trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: execute tests
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation:${DRONE_COMMIT_SHA}
    commands:
      - sh bin/cs.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
  - name: upload serenity report
    image: amazon/aws-cli
    commands:
      - > # yaml folded style
        aws s3 cp
        --recursive /drone/src/target/site/serenity/ s3://cs-integration-testing-s3/serenity-reports/$${DRONE_BUILD_NUMBER}_CS/
        --sse aws:kms
        --sse-kms-key-id $${AWS_KMS_KEY}
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_KMS_KEY:
        from_secret: aws_kms_key_id
    depends_on:
      - execute tests
    when:
      status:
        - success
        - failure

services:
  - name: selenium
    image: selenium/hub

  - name: chrome44
    image: selenium/node-chrome
    environment:
      DISPLAY: :99.0
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
---
kind: pipeline
type: kubernetes
name: MPAM-1-Regression
depends_on:
  - CS-Regression
trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: execute tests
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation:${DRONE_COMMIT_SHA}
    commands:
      - sh bin/mpam1.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
  - name: upload serenity report
    image: amazon/aws-cli
    commands:
      - > # yaml folded style
        aws s3 cp
        --recursive /drone/src/target/site/serenity/ s3://cs-integration-testing-s3/serenity-reports/$${DRONE_BUILD_NUMBER}_MPAM1/
        --sse aws:kms
        --sse-kms-key-id $${AWS_KMS_KEY}
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_KMS_KEY:
        from_secret: aws_kms_key_id
    depends_on:
      - execute tests
    when:
      status:
        - success
        - failure

services:
  - name: selenium
    image: selenium/hub

  - name: chrome55
    image: selenium/node-chrome
    environment:
      DISPLAY: :99.0
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444