---
kind: pipeline
type: kubernetes
name: SMOKE
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/smoke.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: DCU-Regression
depends_on:
  - SMOKE
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/dcu.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: CS-Regression
depends_on:
  - DCU-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/cs.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: MPAM-1-Regression
depends_on:
  - CS-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/mpam1.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: MPAM-2-Regression
depends_on:
  - MPAM-1-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/mpam2.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: COMP-Regression
depends_on:
  - MPAM-2-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/comp.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: BF-Regression
depends_on:
  - COMP-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/bf.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: POGR-Regression
depends_on:
  - BF-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/pogr.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: IEDET-Regression
depends_on:
  - POGR-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/iedet.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: TO-Regression
depends_on:
  - IEDET-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/to.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0

---
kind: pipeline
type: kubernetes
name: WCS-Regression
depends_on:
  - TO-Regression
trigger:
  branch:
    - main
    - nm_qax
  event:
    - push

resources:
  requests:
    cpu: 1000
    memory: 2000MiB

steps:

  - name: execute tests
    image: maven:3.8.6-eclipse-temurin-11-focal
    commands:
      - sh bin/wcs.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - clone

services:
  - name: selenium
    image: selenium/standalone-chrome:4.5.2
    environment:
      DISPLAY: :99.0
