---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build & push
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
    tags:
      - build_${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_ROBOT_PASSWORD
    DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
  when:
    event:
      - push

- name: build & push latest
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
    tags:
      - latest
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_ROBOT_PASSWORD
    DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
  when:
    branch:
      - master
    event:
      - push

- name: execute-tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/hocs-serenity-automation
  commands:
  - sh bin/smoke-tests.sh
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: artifactory_password
    ARTIFACTORY_USERNAME:
      from_secret: artifactory_username
  when:
    branch:
    - master
    event:
    - push

- name: upload-serenity-report
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: cs-integration-testing-s3
    region: eu-west-2
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: /drone/src/target/site/serenity/**/*
    target: /reports/$${DRONE_BUILD_NUMBER}/
  when:
    branch:
    - master
    event:
    - push
    status:
    - success
    - failure

services:
- name: selenium
  pull: if-not-exists
  image: selenium/hub

- name: chrome
  pull: if-not-exists
  image: selenium/node-chrome
  environment:
    DISPLAY: :99.0
    HUB_PORT_4444_TCP_ADDR: selenium
    HUB_PORT_4444_TCP_PORT: 4444

- name: firefox
  pull: if-not-exists
  image: selenium/node-firefox
  environment:
    DISPLAY: :98.0
    HUB_PORT_4444_TCP_ADDR: selenium
    HUB_PORT_4444_TCP_PORT: 4444

- name: dnd
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
