---
kind: pipeline
type: kubernetes
name: default
trigger:
  event:
    - push

steps:
  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_PASSWORD
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on: [ ]

  - name: build & push latest
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
      tags:
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_PASSWORD
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        - main
    depends_on: [ ]

  - name: build & push latest2
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
      tags:
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_PASSWORD
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        - main
    depends_on: [ ]

  - name: execute tests
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation
    commands:
      - sh bin/smoke-tests.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - build & push
      - build & push latest

  - name: execute tests2
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation
    commands:
      - sh bin/smoke-tests2.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory_password
      ARTIFACTORY_USERNAME:
        from_secret: artifactory_username
    depends_on:
      - build & push
      - build & push latest2

  - name: upload serenity report
    image: amazon/aws-cli
    commands:
      - > # yaml folded style
        aws s3 cp
        --recursive /drone/src/target/site/serenity/ s3://cs-integration-testing-s3/serenity-reports/$${DRONE_BUILD_NUMBER}_$(date +'%Y-%m-%d_%H-%M')/
        --sse aws:kms
        --sse-kms-key-id $${AWS_KMS_KEY}
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_KMS_KEY:
        from_secret: aws_kms_key_id
    depends_on:
      - execute tests
    when:
      status:
        - success
        - failure

  - name: upload serenity report2
    image: amazon/aws-cli
    commands:
      - > # yaml folded style
        aws s3 cp
        --recursive /drone/src/target/site/serenity/ s3://cs-integration-testing-s3/serenity-reports/$${DRONE_BUILD_NUMBER}_$(date +'%Y-%m-%d_%H-%M')/
        --sse aws:kms
        --sse-kms-key-id $${AWS_KMS_KEY}
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_KMS_KEY:
        from_secret: aws_kms_key_id
    depends_on:
      - execute tests2
    when:
      status:
        - success
        - failure

services:
  - name: selenium
    image: selenium/hub

  - name: zalenium
    image: dosel/zalenium
    commands:
      - sh bin/zal.sh

  - name: chrome1
    image: selenium/node-chrome
    environment:
      DISPLAY: :99.0
      HUB_PORT_4444_TCP_ADDR: zalenium
      HUB_PORT_4444_TCP_PORT: 4444

  - name: chrome2
    image: selenium/node-chrome
    environment:
      DISPLAY: :99.0
      HUB_PORT_4444_TCP_ADDR: zalenium
      HUB_PORT_4444_TCP_PORT: 4444
