pipeline:

  my-build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs_serenity_automation .
      - docker run hocs_serenity_automation
    when:
      branch: master
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+hocs
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
    tags:
      - build-${DRONE_BUILD_NUMBER}
      - latest
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-serenity-automation quay.io/ukhomeofficedigital/hocs-serenity-automation:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/hocs-serenity-automation:$${DRONE_TAG}
    when:
      event: tag

  execute-tests:
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation
    secrets:
       - artifactory_username
       - artifactory_password
    commands:
      - sh bin/demo.sh
    when:
      branch: master
      event: push

services:
  selenium:
    image: selenium/hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome
    links:
    - selenium-hub:hub
    environment:
       HUB_PORT_4444_TCP_ADDR: hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

  firefox:
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
    links:
    - selenium-hub:hub